-- English Food Database - Complete English Food Database
-- This file contains only English food names for English language users
-- Total foods: 339

-- Clear existing data first (only English foods)
DELETE FROM foods WHERE name_en IS NOT NULL AND name_en != '' AND name_tr = '';

-- Insert English food data
INSERT INTO foods (name, name_tr, name_en, calories_per_100g, protein_g_per_100g, carb_g_per_100g, fat_g_per_100g, fiber_g_per_100g, category, is_active, created_at, updated_at)
VALUES
  ('Apple, Red Delicious', 'Kırmızı Elma', 'Apple, Red Delicious', 52, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Granny Smith', 'Yeşil Elma', 'Apple, Granny Smith', 58, 0.4, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Fuji', 'Fuji Elması', 'Apple, Fuji', 59, 0.3, 15, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Gala', 'Gala Elması', 'Apple, Gala', 57, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Golden Delicious', 'Altın Elma', 'Apple, Golden Delicious', 57, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, McIntosh', 'McIntosh Elması', 'Apple, McIntosh', 52, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Honeycrisp', 'Bal Kıtır Elma', 'Apple, Honeycrisp', 52, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Pink Lady', 'Pembe Hanım Elması', 'Apple, Pink Lady', 52, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Braeburn', 'Braeburn Elması', 'Apple, Braeburn', 52, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Apple, Empire', 'İmparatorluk Elması', 'Apple, Empire', 52, 0.3, 14, 0.2, 2.4, 'fruit', true, NOW(), NOW()),
  ('Banana, Yellow', 'Sarı Muz', 'Banana, Yellow', 89, 1.1, 23, 0.3, 2.6, 'fruit', true, NOW(), NOW()),
  ('Banana, Green', 'Yeşil Muz', 'Banana, Green', 89, 1.1, 23, 0.3, 2.6, 'fruit', true, NOW(), NOW()),
  ('Banana, Red', 'Kırmızı Muz', 'Banana, Red', 89, 1.1, 23, 0.3, 2.6, 'fruit', true, NOW(), NOW()),
  ('Banana, Plantain', 'Muz Ağacı', 'Banana, Plantain', 122, 1.3, 32, 0.4, 2.3, 'fruit', true, NOW(), NOW()),
  ('Orange, Navel', 'Göbekli Portakal', 'Orange, Navel', 47, 0.9, 11.8, 0.1, 2, 'fruit', true, NOW(), NOW()),
  ('Orange, Valencia', 'Valencia Portakalı', 'Orange, Valencia', 47, 0.9, 11.8, 0.1, 2, 'fruit', true, NOW(), NOW()),
  ('Orange, Blood', 'Kan Portakalı', 'Orange, Blood', 47, 0.9, 11.8, 0.1, 2, 'fruit', true, NOW(), NOW()),
  ('Grape, Red', 'Kırmızı Üzüm', 'Grape, Red', 62, 0.6, 16, 0.2, 1, 'fruit', true, NOW(), NOW()),
  ('Grape, Green', 'Yeşil Üzüm', 'Grape, Green', 62, 0.6, 16, 0.2, 1, 'fruit', true, NOW(), NOW()),
  ('Grape, Black', 'Siyah Üzüm', 'Grape, Black', 62, 0.6, 16, 0.2, 1, 'fruit', true, NOW(), NOW()),
  ('Strawberry', 'Çilek', 'Strawberry', 31, 0.6, 7.6, 0.2, 1.8, 'fruit', true, NOW(), NOW()),
  ('Blueberry', 'Yaban Mersini', 'Blueberry', 57, 0.7, 14.5, 0.3, 2.4, 'fruit', true, NOW(), NOW()),
  ('Raspberry', 'Ahududu', 'Raspberry', 52, 1.2, 11.9, 0.7, 6.5, 'fruit', true, NOW(), NOW()),
  ('Blackberry', 'Böğürtlen', 'Blackberry', 43, 1.4, 9.6, 0.5, 5.3, 'fruit', true, NOW(), NOW()),
  ('Cranberry', 'Kızılcık', 'Cranberry', 46, 0.4, 12.2, 0.1, 4.6, 'fruit', true, NOW(), NOW()),
  ('Cherry, Sweet', 'Tatlı Kiraz', 'Cherry, Sweet', 63, 1.1, 16, 0.2, 2.1, 'fruit', true, NOW(), NOW()),
  ('Cherry, Sour', 'Ekşi Kiraz', 'Cherry, Sour', 50, 1, 12.2, 0.3, 1.6, 'fruit', true, NOW(), NOW()),
  ('Peach', 'Şeftali', 'Peach', 42, 0.9, 10.1, 0.3, 1.5, 'fruit', true, NOW(), NOW()),
  ('Pear', 'Armut', 'Pear', 57, 0.4, 15.2, 0.1, 3.1, 'fruit', true, NOW(), NOW()),
  ('Plum', 'Erik', 'Plum', 46, 0.7, 11.4, 0.3, 1.4, 'fruit', true, NOW(), NOW()),
  ('Apricot', 'Kayısı', 'Apricot', 48, 1.4, 11.1, 0.4, 2, 'fruit', true, NOW(), NOW()),
  ('Fig', 'İncir', 'Fig', 74, 0.8, 19.2, 0.3, 2.9, 'fruit', true, NOW(), NOW()),
  ('Date', 'Hurma', 'Date', 277, 1.8, 75, 0.2, 6.7, 'fruit', true, NOW(), NOW()),
  ('Kiwi', 'Kivi', 'Kiwi', 58, 1.1, 14, 0.4, 3, 'fruit', true, NOW(), NOW()),
  ('Mango', 'Mango', 'Mango', 60, 0.8, 15, 0.4, 1.6, 'fruit', true, NOW(), NOW()),
  ('Pineapple', 'Ananas', 'Pineapple', 50, 0.5, 13.1, 0.1, 1.4, 'fruit', true, NOW(), NOW()),
  ('Papaya', 'Papaya', 'Papaya', 43, 0.5, 11, 0.3, 1.7, 'fruit', true, NOW(), NOW()),
  ('Pomegranate', 'Nar', 'Pomegranate', 83, 1.7, 18.7, 1.2, 4, 'fruit', true, NOW(), NOW()),
  ('Watermelon', 'Karpuz', 'Watermelon', 30, 0.6, 7.6, 0.2, 0.4, 'fruit', true, NOW(), NOW()),
  ('Cantaloupe', 'Kavun', 'Cantaloupe', 34, 0.8, 8.2, 0.2, 0.8, 'fruit', true, NOW(), NOW()),
  ('Grapefruit', 'Greyfurt', 'Greyfurt', 42, 0.8, 10.7, 0.1, 1.6, 'fruit', true, NOW(), NOW()),
  ('Lemon', 'Limon', 'Lemon', 29, 1.1, 9.3, 0.3, 2.8, 'fruit', true, NOW(), NOW()),
  ('Lime', 'Misket Limonu', 'Lime', 30, 0.7, 10.5, 0.2, 2.8, 'fruit', true, NOW(), NOW()),
  ('Avocado', 'Avokado', 'Avocado', 160, 2, 8.5, 14.7, 6.7, 'fruit', true, NOW(), NOW()),
  ('Coconut', 'Hindistan Cevizi', 'Coconut', 354, 3.3, 15.2, 33.5, 9, 'fruit', true, NOW(), NOW()),
  ('Carrot', 'Havuç', 'Carrot', 41, 0.9, 9.6, 0.2, 2.8, 'vegetable', true, NOW(), NOW()),
  ('Potato', 'Patates', 'Potato', 77, 2, 17, 0.1, 2.2, 'vegetable', true, NOW(), NOW()),
  ('Potato, Sweet', 'Tatlı Patates', 'Potato, Sweet', 86, 1.6, 20.1, 0.1, 3, 'vegetable', true, NOW(), NOW()),
  ('Onion', 'Soğan', 'Onion', 40, 1.1, 9.3, 0.1, 1.7, 'vegetable', true, NOW(), NOW()),
  ('Garlic', 'Sarımsak', 'Garlic', 149, 6.4, 33.1, 0.5, 2.1, 'vegetable', true, NOW(), NOW()),
  ('Tomato', 'Domates', 'Tomato', 18, 0.9, 3.9, 0.2, 1.2, 'vegetable', true, NOW(), NOW()),
  ('Lettuce', 'Marul', 'Lettuce', 15, 1.4, 2.9, 0.2, 1.3, 'vegetable', true, NOW(), NOW()),
  ('Spinach', 'Ispanak', 'Spinach', 23, 2.9, 3.6, 0.4, 2.2, 'vegetable', true, NOW(), NOW()),
  ('Kale', 'Kara Lahana', 'Kale', 35, 2.9, 4.4, 1.5, 4.1, 'vegetable', true, NOW(), NOW()),
  ('Broccoli', 'Brokoli', 'Broccoli', 32, 2.6, 6.3, 0.3, 2.4, 'vegetable', true, NOW(), NOW()),
  ('Cauliflower', 'Karnabahar', 'Cauliflower', 25, 1.9, 5, 0.3, 2, 'vegetable', true, NOW(), NOW()),
  ('Cabbage', 'Lahana', 'Cabbage', 25, 1.3, 5.8, 0.1, 2.5, 'vegetable', true, NOW(), NOW()),
  ('Bell Pepper', 'Dolmalık Biber', 'Bell Pepper', 31, 0.9, 7.3, 0.3, 2.5, 'vegetable', true, NOW(), NOW()),
  ('Cucumber', 'Salatalık', 'Cucumber', 16, 0.7, 4, 0.1, 0.5, 'vegetable', true, NOW(), NOW()),
  ('Zucchini', 'Kabak', 'Zucchini', 17, 1.2, 3.1, 0.3, 1, 'vegetable', true, NOW(), NOW()),
  ('Eggplant', 'Patlıcan', 'Eggplant', 25, 1, 5.9, 0.2, 3, 'vegetable', true, NOW(), NOW()),
  ('Mushroom', 'Mantar', 'Mushroom', 22, 3.1, 3.3, 0.3, 1, 'vegetable', true, NOW(), NOW()),
  ('Asparagus', 'Kuşkonmaz', 'Asparagus', 20, 2.2, 3.9, 0.1, 2.1, 'vegetable', true, NOW(), NOW()),
  ('Celery', 'Kereviz', 'Celery', 16, 0.7, 3, 0.2, 1.6, 'vegetable', true, NOW(), NOW()),
  ('Radish', 'Turp', 'Radish', 16, 0.7, 3.4, 0.1, 1.6, 'vegetable', true, NOW(), NOW()),
  ('Beet', 'Pancar', 'Beet', 43, 1.6, 9.6, 0.2, 2.8, 'vegetable', true, NOW(), NOW()),
  ('Turnip', 'Şalgam', 'Turnip', 28, 0.9, 6.4, 0.1, 1.8, 'vegetable', true, NOW(), NOW()),
  ('Corn', 'Mısır', 'Corn', 86, 3.3, 19, 1.2, 2.7, 'vegetable', true, NOW(), NOW()),
  ('Green Bean', 'Yeşil Fasulye', 'Green Bean', 31, 1.8, 7, 0.2, 2.7, 'vegetable', true, NOW(), NOW()),
  ('Artichoke', 'Enginar', 'Artichoke', 47, 3.3, 10.5, 0.2, 5.4, 'vegetable', true, NOW(), NOW()),
  ('Brussels Sprout', 'Brüksel Lahanası', 'Brussels Sprout', 43, 3.4, 8.9, 0.3, 3.8, 'vegetable', true, NOW(), NOW()),
  ('Okra', 'Bamya', 'Okra', 33, 1.9, 7.5, 0.2, 3.2, 'vegetable', true, NOW(), NOW()),
  ('Leek', 'Pırasa', 'Leek', 61, 1.5, 14.2, 0.3, 1.8, 'vegetable', true, NOW(), NOW()),
  ('Fennel', 'Rezene', 'Fennel', 31, 1.2, 7.3, 0.2, 3.1, 'vegetable', true, NOW(), NOW()),
  ('Endive', 'Hindiba', 'Endive', 17, 1.3, 3.4, 0.2, 3.1, 'vegetable', true, NOW(), NOW()),
  ('Swiss Chard', 'İsviçre Pazı', 'Swiss Chard', 19, 1.8, 3.7, 0.2, 1.6, 'vegetable', true, NOW(), NOW()),
  ('Watercress', 'Su Teresi', 'Watercress', 11, 2.3, 1.3, 0.1, 0.5, 'vegetable', true, NOW(), NOW()),
  ('Arugula', 'Roka', 'Arugula', 25, 2.6, 3.7, 0.7, 1.6, 'vegetable', true, NOW(), NOW()),
  ('Bok Choy', 'Bok Choy', 'Bok Choy', 13, 1.5, 2.2, 0.2, 1, 'vegetable', true, NOW(), NOW()),
  ('Parsley', 'Maydanoz', 'Parsley', 36, 3, 6.3, 0.8, 3.3, 'vegetable', true, NOW(), NOW()),
  ('Dill', 'Dereotu', 'Dill', 43, 3.5, 7, 1.1, 2.1, 'vegetable', true, NOW(), NOW()),
  ('Cilantro', 'Kişniş', 'Cilantro', 23, 2.1, 3.7, 0.5, 2.8, 'vegetable', true, NOW(), NOW()),
  ('Ginger', 'Zencefil', 'Ginger', 80, 1.8, 17.8, 0.8, 2, 'vegetable', true, NOW(), NOW()),
  ('Beef Steak', 'Biftek', 'Beef Steak', 250, 26, 0, 15, 0, 'protein', true, NOW(), NOW()),
  ('Beef Ribeye', 'Ribeye Biftek', 'Beef Ribeye', 291, 26, 0, 20, 0, 'protein', true, NOW(), NOW()),
  ('Beef Sirloin', 'Sırlık Biftek', 'Beef Sirloin', 250, 26, 0, 15, 0, 'protein', true, NOW(), NOW()),
  ('Beef Tenderloin', 'Bonfile', 'Beef Tenderloin', 267, 26, 0, 17, 0, 'protein', true, NOW(), NOW()),
  ('Beef Chuck', 'Boyun Eti', 'Beef Chuck', 250, 26, 0, 15, 0, 'protein', true, NOW(), NOW()),
  ('Beef Brisket', 'Göğüs Eti', 'Beef Brisket', 250, 26, 0, 15, 0, 'protein', true, NOW(), NOW()),
  ('Lamb Chops', 'Pirzola, Kuzu', 'Lamb Chops', 280, 25, 0, 18, 0, 'protein', true, NOW(), NOW()),
  ('Lamb Leg', 'Kuzu Budu', 'Lamb Leg', 280, 25, 0, 18, 0, 'protein', true, NOW(), NOW()),
  ('Lamb Shoulder', 'Kuzu Omzu', 'Lamb Shoulder', 280, 25, 0, 18, 0, 'protein', true, NOW(), NOW()),
  ('Chicken Breast', 'Tavuk Göğsü', 'Chicken Breast', 165, 31, 0, 3.6, 0, 'protein', true, NOW(), NOW()),
  ('Chicken Thigh', 'Tavuk Butu', 'Chicken Thigh', 209, 26, 0, 10.9, 0, 'protein', true, NOW(), NOW()),
  ('Chicken Wing', 'Tavuk Kanadı', 'Chicken Wing', 203, 30.5, 0, 8.1, 0, 'protein', true, NOW(), NOW()),
  ('Chicken Drumstick', 'Tavuk Bacağı', 'Chicken Drumstick', 172, 28.3, 0, 5.7, 0, 'protein', true, NOW(), NOW()),
  ('Whole Chicken', 'Bütün Tavuk', 'Whole Chicken', 239, 27.3, 0, 13.6, 0, 'protein', true, NOW(), NOW()),
  ('Turkey Breast', 'Hindi Göğsü', 'Turkey Breast', 135, 30, 0, 1.7, 0, 'protein', true, NOW(), NOW()),
  ('Turkey Thigh', 'Hindi Butu', 'Turkey Thigh', 189, 23, 0, 10, 0, 'protein', true, NOW(), NOW()),
  ('Salmon', 'Somon', 'Salmon', 208, 22, 0, 12, 0, 'protein', true, NOW(), NOW()),
  ('Tuna', 'Ton Balığı', 'Tuna', 109, 24, 0, 1, 0, 'protein', true, NOW(), NOW()),
  ('Cod', 'Morina', 'Cod', 82, 18, 0, 0.7, 0, 'protein', true, NOW(), NOW()),
  ('Halibut', 'Pisi Balığı', 'Halibut', 111, 22, 0, 2, 0, 'protein', true, NOW(), NOW()),
  ('Mackerel', 'Uskumru', 'Mackerel', 205, 19, 0, 14, 0, 'protein', true, NOW(), NOW()),
  ('Sardines', 'Sardalya', 'Sardines', 208, 25, 0, 11, 0, 'protein', true, NOW(), NOW()),
  ('Trout', 'Alabalık', 'Trout', 119, 20, 0, 3.5, 0, 'protein', true, NOW(), NOW()),
  ('Shrimp', 'Karides', 'Shrimp', 99, 24, 0, 0.3, 0, 'protein', true, NOW(), NOW()),
  ('Crab', 'Yengeç', 'Crab', 97, 20.1, 0, 1.5, 0, 'protein', true, NOW(), NOW()),
  ('Lobster', 'Istakoz', 'Lobster', 89, 18.8, 0, 0.9, 0, 'protein', true, NOW(), NOW()),
  ('Scallops', 'Tarak', 'Scallops', 69, 12.1, 2.4, 0.4, 0, 'protein', true, NOW(), NOW()),
  ('Mussels', 'Midye', 'Mussels', 86, 11.9, 3.7, 2.2, 0, 'protein', true, NOW(), NOW()),
  ('Clams', 'İstiridye', 'Clams', 86, 14.7, 2.6, 0.9, 0, 'protein', true, NOW(), NOW()),
  ('Eggs', 'Yumurta', 'Eggs', 148, 12.4, 1, 10, 0, 'protein', true, NOW(), NOW()),
  ('Egg Whites', 'Yumurta Akı', 'Egg Whites', 52, 11, 0.7, 0.2, 0, 'protein', true, NOW(), NOW()),
  ('Egg Yolks', 'Yumurta Sarısı', 'Egg Yolks', 322, 16, 3.6, 27, 0, 'protein', true, NOW(), NOW()),
  ('Whole Milk', 'Tam Yağlı Süt', 'Whole Milk', 61, 3.2, 4.7, 3.3, 0, 'dairy', true, NOW(), NOW()),
  ('2% Milk', 'Az Yağlı Süt', '2% Milk', 50, 3.3, 4.8, 2, 0, 'dairy', true, NOW(), NOW()),
  ('1% Milk', 'Düşük Yağlı Süt', '1% Milk', 42, 3.4, 5, 1, 0, 'dairy', true, NOW(), NOW()),
  ('Skim Milk', 'Yağsız Süt', 'Skim Milk', 34, 3.4, 5, 0.2, 0, 'dairy', true, NOW(), NOW()),
  ('Buttermilk', 'Ayran', 'Buttermilk', 40, 3.3, 4.8, 0.9, 0, 'dairy', true, NOW(), NOW()),
  ('Goat Milk', 'Keçi Sütü', 'Goat Milk', 69, 3.6, 4.5, 4.1, 0, 'dairy', true, NOW(), NOW()),
  ('Cheddar Cheese', 'Çedar Peyniri', 'Cheddar Cheese', 403, 25, 1.3, 33, 0, 'dairy', true, NOW(), NOW()),
  ('Mozzarella Cheese', 'Mozzarella Peyniri', 'Mozzarella Cheese', 280, 22, 2.2, 22, 0, 'dairy', true, NOW(), NOW()),
  ('Swiss Cheese', 'İsviçre Peyniri', 'Swiss Cheese', 380, 27, 1.4, 28, 0, 'dairy', true, NOW(), NOW()),
  ('Parmesan Cheese', 'Parmesan Peyniri', 'Parmesan Cheese', 431, 38, 4.1, 29, 0, 'dairy', true, NOW(), NOW()),
  ('Blue Cheese', 'Rokfor Peyniri', 'Blue Cheese', 353, 21, 2.3, 29, 0, 'dairy', true, NOW(), NOW()),
  ('Feta Cheese', 'Beyaz Peynir', 'Feta Cheese', 264, 14, 4.1, 21, 0, 'dairy', true, NOW(), NOW()),
  ('Cottage Cheese', 'Lor Peyniri', 'Cottage Cheese', 98, 11, 3.4, 4.3, 0, 'dairy', true, NOW(), NOW()),
  ('Ricotta Cheese', 'Ricotta Peyniri', 'Ricotta Cheese', 174, 11, 3, 13, 0, 'dairy', true, NOW(), NOW()),
  ('Cream Cheese', 'Krem Peyniri', 'Cream Cheese', 342, 6, 4.1, 34, 0, 'dairy', true, NOW(), NOW()),
  ('Goat Cheese', 'Keçi Peyniri', 'Goat Cheese', 364, 22, 2.5, 30, 0, 'dairy', true, NOW(), NOW()),
  ('Greek Yogurt', 'Yunan Yoğurdu', 'Greek Yogurt', 59, 10, 3.6, 0.4, 0, 'dairy', true, NOW(), NOW()),
  ('Plain Yogurt', 'Sade Yoğurt', 'Plain Yogurt', 61, 3.5, 4.7, 3.3, 0, 'dairy', true, NOW(), NOW()),
  ('Vanilla Yogurt', 'Vanilyalı Yoğurt', 'Vanilla Yogurt', 113, 5, 17.3, 2.9, 0, 'dairy', true, NOW(), NOW()),
  ('Strawberry Yogurt', 'Çilekli Yoğurt', 'Strawberry Yogurt', 113, 5, 17.3, 2.9, 0, 'dairy', true, NOW(), NOW()),
  ('Butter', 'Tereyağı', 'Butter', 717, 0.9, 0.1, 81, 0, 'dairy', true, NOW(), NOW()),
  ('Margarine', 'Margarin', 'Margarine', 717, 0.2, 0.7, 81, 0, 'dairy', true, NOW(), NOW()),
  ('White Bread', 'Beyaz Ekmek', 'White Bread', 270, 9.4, 49.2, 3.6, 2.3, 'grain', true, NOW(), NOW()),
  ('Whole Wheat Bread', 'Tam Buğday Ekmeği', 'Whole Wheat Bread', 247, 13.4, 41.3, 4.2, 6, 'grain', true, NOW(), NOW()),
  ('Sourdough Bread', 'Ekşi Mayalı Ekmek', 'Sourdough Bread', 289, 11.6, 56.8, 2.2, 2.4, 'grain', true, NOW(), NOW()),
  ('Rye Bread', 'Çavdar Ekmeği', 'Rye Bread', 258, 8.5, 48.3, 3.3, 5.8, 'grain', true, NOW(), NOW()),
  ('Pita Bread', 'Pita Ekmeği', 'Pita Bread', 275, 9.1, 55.7, 1.2, 2.2, 'grain', true, NOW(), NOW()),
  ('Bagel', 'Simit', 'Bagel', 257, 10.1, 50.9, 1.7, 2.3, 'grain', true, NOW(), NOW()),
  ('White Rice', 'Beyaz Pirinç', 'White Rice', 365, 7.1, 80, 0.7, 1.3, 'grain', true, NOW(), NOW()),
  ('Brown Rice', 'Kahverengi Pirinç', 'Brown Rice', 370, 7.9, 77, 2.9, 3.5, 'grain', true, NOW(), NOW()),
  ('Basmati Rice', 'Basmati Pirinci', 'Basmati Rice', 365, 7.1, 80, 0.7, 1.3, 'grain', true, NOW(), NOW()),
  ('Jasmine Rice', 'Jasmine Pirinci', 'Jasmine Rice', 365, 7.1, 80, 0.7, 1.3, 'grain', true, NOW(), NOW()),
  ('Spaghetti', 'Spagetti Makarnası', 'Spaghetti', 371, 13, 75, 1.5, 3.2, 'grain', true, NOW(), NOW()),
  ('Penne', 'Penne Makarnası', 'Penne', 371, 13, 75, 1.5, 3.2, 'grain', true, NOW(), NOW()),
  ('Fettuccine', 'Fettuccine Makarnası', 'Fettuccine', 371, 13, 75, 1.5, 3.2, 'grain', true, NOW(), NOW()),
  ('Linguine', 'Linguine Makarnası', 'Linguine', 371, 13, 75, 1.5, 3.2, 'grain', true, NOW(), NOW()),
  ('Rigatoni', 'Rigatoni Makarnası', 'Rigatoni', 371, 13, 75, 1.5, 3.2, 'grain', true, NOW(), NOW()),
  ('Oatmeal', 'Yulaf Ezmesi', 'Oatmeal', 389, 16.9, 66.3, 6.9, 10.6, 'grain', true, NOW(), NOW()),
  ('Quinoa', 'Kinoa', 'Quinoa', 368, 14.1, 64.2, 6.1, 7, 'grain', true, NOW(), NOW()),
  ('Barley', 'Arpa', 'Barley', 354, 12.5, 73.5, 2.3, 17.3, 'grain', true, NOW(), NOW()),
  ('Bulgur', 'Bulgur', 'Bulgur', 342, 12.3, 75.9, 1.3, 18.3, 'grain', true, NOW(), NOW()),
  ('Hamburger', 'Hamburger', 'Hamburger', 354, 16, 33, 17, 2, 'fast_food', true, NOW(), NOW()),
  ('Cheeseburger', 'Peynirli Hamburger', 'Cheeseburger', 313, 15, 33, 12, 2, 'fast_food', true, NOW(), NOW()),
  ('Big Mac', 'Big Mac', 'Big Mac', 550, 25, 45, 33, 3, 'fast_food', true, NOW(), NOW()),
  ('Quarter Pounder', 'Çeyrek Pounder', 'Quarter Pounder', 520, 25, 42, 26, 3, 'fast_food', true, NOW(), NOW()),
  ('Whopper', 'Whopper', 'Whopper', 660, 28, 49, 40, 2, 'fast_food', true, NOW(), NOW()),
  ('Double Whopper', 'Çift Whopper', 'Double Whopper', 900, 48, 49, 58, 2, 'fast_food', true, NOW(), NOW()),
  ('Hot Dog', 'Sosisli', 'Hot Dog', 290, 10, 24, 18, 1, 'fast_food', true, NOW(), NOW()),
  ('Chili Dog', 'Acılı Sosisli', 'Chili Dog', 350, 15, 28, 20, 2, 'fast_food', true, NOW(), NOW()),
  ('Corn Dog', 'Mısır Sosisli', 'Corn Dog', 250, 8, 25, 12, 1, 'fast_food', true, NOW(), NOW()),
  ('Pizza, Margherita', 'Pizza, Margherita', 'Pizza, Margherita', 266, 11, 33, 10, 2, 'fast_food', true, NOW(), NOW()),
  ('Pizza, Pepperoni', 'Pizza, Pepperoni', 'Pizza, Pepperoni', 298, 12, 33, 12, 2, 'fast_food', true, NOW(), NOW()),
  ('Pizza, Cheese', 'Pizza, Peynirli', 'Pizza, Cheese', 266, 11, 33, 10, 2, 'fast_food', true, NOW(), NOW()),
  ('Pizza, Supreme', 'Pizza, Supreme', 'Pizza, Supreme', 312, 13, 35, 14, 3, 'fast_food', true, NOW(), NOW()),
  ('Pizza, Hawaiian', 'Pizza, Hawaii', 'Pizza, Hawaiian', 280, 12, 34, 11, 2, 'fast_food', true, NOW(), NOW()),
  ('Pizza, Meat Lovers', 'Pizza, Et Severler', 'Pizza, Meat Lovers', 320, 15, 33, 16, 2, 'fast_food', true, NOW(), NOW()),
  ('Fish and Chips', 'Balık ve Cips', 'Fish and Chips', 595, 18, 68, 28, 3, 'fast_food', true, NOW(), NOW()),
  ('Fish Sandwich', 'Balık Sandviçi', 'Fish Sandwich', 397, 18, 38, 18, 2, 'fast_food', true, NOW(), NOW()),
  ('Fish Tacos', 'Balık Tacos', 'Fish Tacos', 280, 18, 25, 12, 3, 'fast_food', true, NOW(), NOW()),
  ('Fried Shrimp', 'Kızarmış Karides', 'Fried Shrimp', 242, 18, 12, 12, 1, 'fast_food', true, NOW(), NOW()),
  ('French Fries', 'Patates Kızartması', 'French Fries', 365, 4, 63, 11, 6, 'fast_food', true, NOW(), NOW()),
  ('Onion Rings', 'Soğan Halkası', 'Onion Rings', 411, 5, 41, 25, 3, 'fast_food', true, NOW(), NOW()),
  ('Mozzarella Sticks', 'Mozzarella Çubukları', 'Mozzarella Sticks', 280, 15, 18, 16, 1, 'fast_food', true, NOW(), NOW()),
  ('Chicken Wings', 'Tavuk Kanadı', 'Chicken Wings', 203, 30.5, 0, 8.1, 0, 'fast_food', true, NOW(), NOW()),
  ('Buffalo Wings', 'Buffalo Kanatları', 'Buffalo Wings', 250, 25, 5, 15, 0, 'fast_food', true, NOW(), NOW()),
  ('Chicken Nuggets', 'Tavuk Nugget', 'Chicken Nuggets', 296, 16, 15, 20, 1, 'fast_food', true, NOW(), NOW()),
  ('Chicken Sandwich', 'Tavuk Sandviçi', 'Chicken Sandwich', 440, 25, 35, 22, 2, 'fast_food', true, NOW(), NOW()),
  ('Chicken Tenders', 'Tavuk Şeridi', 'Chicken Tenders', 246, 22, 11, 12, 1, 'fast_food', true, NOW(), NOW()),
  ('Tacos', 'Tacos', 'Tacos', 226, 8, 20, 12, 3, 'fast_food', true, NOW(), NOW()),
  ('Burritos', 'Burrito', 'Burritos', 206, 7, 28, 6, 3, 'fast_food', true, NOW(), NOW()),
  ('Nachos', 'Nachos', 'Nachos', 536, 11, 34, 40, 5, 'fast_food', true, NOW(), NOW()),
  ('Quesadilla', 'Quesadilla', 'Quesadilla', 529, 26, 31, 32, 2, 'fast_food', true, NOW(), NOW()),
  ('Sub Sandwich', 'Alt Sandviçi', 'Sub Sandwich', 280, 15, 30, 12, 3, 'fast_food', true, NOW(), NOW()),
  ('Club Sandwich', 'Kulüp Sandviçi', 'Club Sandwich', 420, 25, 30, 22, 2, 'fast_food', true, NOW(), NOW()),
  ('BLT Sandwich', 'BLT Sandviçi', 'BLT Sandwich', 350, 15, 30, 18, 2, 'fast_food', true, NOW(), NOW()),
  ('Grilled Cheese', 'Izgara Peynirli', 'Grilled Cheese', 400, 18, 30, 22, 1, 'fast_food', true, NOW(), NOW()),
  ('Coffee, Black', 'Siyah Kahve', 'Coffee, Black', 2, 0.3, 0, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Coffee, Latte', 'Latte Kahve', 'Coffee, Latte', 43, 3.2, 4.2, 1.8, 0, 'beverage', true, NOW(), NOW()),
  ('Coffee, Cappuccino', 'Kapuçino', 'Coffee, Cappuccino', 43, 3.2, 4.2, 1.8, 0, 'beverage', true, NOW(), NOW()),
  ('Coffee, Americano', 'Americano Kahve', 'Coffee, Americano', 2, 0.3, 0, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Coffee, Espresso', 'Espresso', 'Coffee, Espresso', 2, 0.3, 0, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Coffee, Mocha', 'Mocha Kahve', 'Coffee, Mocha', 43, 3.2, 4.2, 1.8, 0, 'beverage', true, NOW(), NOW()),
  ('Coffee, Macchiato', 'Macchiato', 'Coffee, Macchiato', 43, 3.2, 4.2, 1.8, 0, 'beverage', true, NOW(), NOW()),
  ('Coffee, Frappuccino', 'Frappuccino', 'Coffee, Frappuccino', 150, 3, 25, 4, 0, 'beverage', true, NOW(), NOW()),
  ('Tea, Black', 'Siyah Çay', 'Tea, Black', 1, 0, 0.3, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Tea, Green', 'Yeşil Çay', 'Tea, Green', 1, 0, 0.3, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Tea, Herbal', 'Bitki Çayı', 'Tea, Herbal', 1, 0, 0.3, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Tea, Oolong', 'Oolong Çayı', 'Tea, Oolong', 1, 0, 0.3, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Tea, White', 'Beyaz Çay', 'Tea, White', 1, 0, 0.3, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Tea, Earl Grey', 'Earl Grey Çayı', 'Tea, Earl Grey', 1, 0, 0.3, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Tea, Chai', 'Chai Çayı', 'Tea, Chai', 1, 0, 0.3, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Cola', 'Kola', 'Soda, Cola', 42, 0, 10.6, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Diet Cola', 'Diyet Kola', 'Soda, Diet Cola', 0, 0, 0, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Pepsi', 'Pepsi', 'Soda, Pepsi', 42, 0, 10.6, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Sprite', 'Sprite', 'Soda, Sprite', 38, 0, 10, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Fanta', 'Fanta', 'Soda, Fanta', 38, 0, 10, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Mountain Dew', 'Mountain Dew', 'Soda, Mountain Dew', 46, 0, 12, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Dr Pepper', 'Dr Pepper', 'Soda, Dr Pepper', 41, 0, 10.4, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Ginger Ale', 'Zencefil Gazozu', 'Soda, Ginger Ale', 38, 0, 10, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Root Beer', 'Root Beer', 'Soda, Root Beer', 41, 0, 10.4, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Orange', 'Portakal Gazozu', 'Soda, Orange', 38, 0, 10, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Soda, Lemon-Lime', 'Limon-Lime Gazozu', 'Soda, Lemon-Lime', 38, 0, 10, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Energy Drink', 'Enerji İçeceği', 'Energy Drink', 46, 0, 11, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Red Bull', 'Red Bull', 'Red Bull', 46, 0, 11, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Monster Energy', 'Monster Energy', 'Monster Energy', 46, 0, 11, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Rockstar Energy', 'Rockstar Energy', 'Rockstar Energy', 46, 0, 11, 0, 0, 'beverage', true, NOW(), NOW()),
  ('Beer, Regular', 'Normal Bira', 'Beer, Regular', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Light', 'Hafif Bira', 'Beer, Light', 29, 0.3, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Dark', 'Koyu Bira', 'Beer, Dark', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, IPA', 'IPA Bira', 'Beer, IPA', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Lager', 'Lager Bira', 'Beer, Lager', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Pilsner', 'Pilsner Bira', 'Beer, Pilsner', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Stout', 'Stout Bira', 'Beer, Stout', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Wheat', 'Buğday Birası', 'Beer, Wheat', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Porter', 'Porter Bira', 'Beer, Porter', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Beer, Ale', 'Ale Bira', 'Beer, Ale', 43, 0.5, 3.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Red', 'Kırmızı Şarap', 'Wine, Red', 85, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, White', 'Beyaz Şarap', 'Wine, White', 82, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Rose', 'Pembe Şarap', 'Wine, Rose', 83, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Champagne', 'Şampanya', 'Wine, Champagne', 84, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Prosecco', 'Prosecco', 'Wine, Prosecco', 84, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Pinot Noir', 'Pinot Noir', 'Wine, Pinot Noir', 85, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Cabernet', 'Cabernet', 'Wine, Cabernet', 85, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Merlot', 'Merlot', 'Wine, Merlot', 85, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Chardonnay', 'Chardonnay', 'Wine, Chardonnay', 82, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Sauvignon Blanc', 'Sauvignon Blanc', 'Wine, Sauvignon Blanc', 82, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Riesling', 'Riesling', 'Wine, Riesling', 82, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Wine, Pinot Grigio', 'Pinot Grigio', 'Wine, Pinot Grigio', 82, 0.1, 2.6, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Whiskey, Bourbon', 'Bourbon Viski', 'Whiskey, Bourbon', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Whiskey, Scotch', 'İskoç Viski', 'Whiskey, Scotch', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Whiskey, Irish', 'İrlanda Viski', 'Whiskey, Irish', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Whiskey, Rye', 'Çavdar Viski', 'Whiskey, Rye', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Whiskey, Tennessee', 'Tennessee Viski', 'Whiskey, Tennessee', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Whiskey, Canadian', 'Kanada Viski', 'Whiskey, Canadian', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Whiskey, Japanese', 'Japon Viski', 'Whiskey, Japanese', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Martini', 'Martini Kokteyli', 'Cocktail, Martini', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Manhattan', 'Manhattan Kokteyli', 'Cocktail, Manhattan', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Old Fashioned', 'Old Fashioned Kokteyli', 'Cocktail, Old Fashioned', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Margarita', 'Margarita Kokteyli', 'Cocktail, Margarita', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Mojito', 'Mojito Kokteyli', 'Cocktail, Mojito', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Daiquiri', 'Daiquiri Kokteyli', 'Cocktail, Daiquiri', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Cosmopolitan', 'Cosmopolitan Kokteyli', 'Cocktail, Cosmopolitan', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Bloody Mary', 'Bloody Mary Kokteyli', 'Cocktail, Bloody Mary', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Pina Colada', 'Pina Colada Kokteyli', 'Cocktail, Pina Colada', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cocktail, Sex on the Beach', 'Sex on the Beach Kokteyli', 'Cocktail, Sex on the Beach', 231, 0, 0.1, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Vodka', 'Votka', 'Vodka', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Rum', 'Rom', 'Rum', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Gin', 'Cin', 'Gin', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Tequila', 'Tekila', 'Tequila', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Brandy', 'Brendi', 'Brandy', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Cognac', 'Konyak', 'Cognac', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Liqueur', 'Likör', 'Liqueur', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Sake', 'Sake', 'Sake', 134, 0.5, 5, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Soju', 'Soju', 'Soju', 231, 0, 0, 0, 0, 'alcohol', true, NOW(), NOW()),
  ('Almonds', 'Badem', 'Almonds', 579, 21.2, 21.6, 49.9, 12.5, 'protein', true, NOW(), NOW()),
  ('Walnuts', 'Ceviz', 'Walnuts', 654, 15.2, 13.7, 65.2, 6.7, 'protein', true, NOW(), NOW()),
  ('Peanuts', 'Fıstık', 'Peanuts', 567, 25.8, 16.1, 49.2, 8.5, 'protein', true, NOW(), NOW()),
  ('Cashews', 'Kaju', 'Cashews', 553, 18.2, 30.2, 43.8, 3.3, 'protein', true, NOW(), NOW()),
  ('Pistachios', 'Antep Fıstığı', 'Pistachios', 560, 20.2, 27.2, 45.3, 10.6, 'protein', true, NOW(), NOW()),
  ('Pecans', 'Pikan Cevizi', 'Pecans', 691, 9.2, 13.9, 72, 9.6, 'protein', true, NOW(), NOW()),
  ('Hazelnuts', 'Fındık', 'Hazelnuts', 628, 15, 16.7, 60.8, 9.7, 'protein', true, NOW(), NOW()),
  ('Macadamia Nuts', 'Macadamia Cevizi', 'Macadamia Nuts', 718, 7.9, 13.8, 75.8, 8.6, 'protein', true, NOW(), NOW()),
  ('Brazil Nuts', 'Brezilya Cevizi', 'Brazil Nuts', 659, 14.3, 12.3, 67.1, 7.5, 'protein', true, NOW(), NOW()),
  ('Pine Nuts', 'Çam Fıstığı', 'Pine Nuts', 673, 13.7, 13.1, 68.4, 3.7, 'protein', true, NOW(), NOW()),
  ('Sunflower Seeds', 'Ayçiçeği Çekirdeği', 'Sunflower Seeds', 584, 20.8, 20, 51.5, 8.6, 'protein', true, NOW(), NOW()),
  ('Pumpkin Seeds', 'Kabak Çekirdeği', 'Pumpkin Seeds', 559, 30.2, 10.7, 49.1, 6, 'protein', true, NOW(), NOW()),
  ('Sesame Seeds', 'Susam', 'Sesame Seeds', 573, 17.7, 23.4, 49.7, 11.8, 'protein', true, NOW(), NOW()),
  ('Chia Seeds', 'Chia Tohumu', 'Chia Seeds', 486, 16.5, 42.1, 30.7, 34.4, 'protein', true, NOW(), NOW()),
  ('Flax Seeds', 'Keten Tohumu', 'Flax Seeds', 534, 18.3, 28.9, 42.2, 27.3, 'protein', true, NOW(), NOW()),
  ('Chocolate Cake', 'Çikolatalı Pasta', 'Chocolate Cake', 371, 4.3, 51.5, 16.4, 2.2, 'dessert', true, NOW(), NOW()),
  ('Vanilla Cake', 'Vanilyalı Pasta', 'Vanilla Cake', 350, 4, 50, 14, 1.5, 'dessert', true, NOW(), NOW()),
  ('Cheesecake', 'Cheesecake', 'Cheesecake', 321, 5.5, 25.2, 22.5, 0.5, 'dessert', true, NOW(), NOW()),
  ('Apple Pie', 'Elmalı Turta', 'Apple Pie', 237, 2.4, 34, 11, 1.9, 'dessert', true, NOW(), NOW()),
  ('Pumpkin Pie', 'Balkabağı Turta', 'Pumpkin Pie', 243, 3.9, 26.4, 13.8, 1.6, 'dessert', true, NOW(), NOW()),
  ('Chocolate Chip Cookies', 'Çikolata Parçacıklı Kurabiye', 'Chocolate Chip Cookies', 488, 5.9, 68.1, 22.9, 2.4, 'dessert', true, NOW(), NOW()),
  ('Brownies', 'Brownie', 'Brownies', 466, 6.2, 50.2, 29.1, 3.1, 'dessert', true, NOW(), NOW()),
  ('Ice Cream, Vanilla', 'Vanilyalı Dondurma', 'Ice Cream, Vanilla', 207, 3.5, 24, 11, 0.7, 'dessert', true, NOW(), NOW()),
  ('Ice Cream, Chocolate', 'Çikolatalı Dondurma', 'Ice Cream, Chocolate', 216, 3.8, 28, 11, 2.3, 'dessert', true, NOW(), NOW()),
  ('Ice Cream, Strawberry', 'Çilekli Dondurma', 'Ice Cream, Strawberry', 192, 3.2, 23, 10, 0.7, 'dessert', true, NOW(), NOW()),
  ('Gelato', 'Gelato', 'Gelato', 207, 3.5, 24, 11, 0.7, 'dessert', true, NOW(), NOW()),
  ('Sorbet', 'Sorbet', 'Sorbet', 127, 0.4, 32, 0.2, 1.2, 'dessert', true, NOW(), NOW()),
  ('Pudding', 'Pudding', 'Pudding', 142, 3.2, 23, 4.7, 0.5, 'dessert', true, NOW(), NOW()),
  ('Tiramisu', 'Tiramisu', 'Tiramisu', 240, 4.6, 25, 14, 0.8, 'dessert', true, NOW(), NOW()),
  ('Creme Brulee', 'Crème Brûlée', 'Creme Brulee', 300, 5, 25, 20, 0, 'dessert', true, NOW(), NOW()),
  ('Pancakes', 'Pankek', 'Pancakes', 227, 6.4, 28, 9.7, 1.2, 'grain', true, NOW(), NOW()),
  ('Waffles', 'Waffle', 'Waffles', 291, 7.9, 37, 12, 2, 'grain', true, NOW(), NOW()),
  ('French Toast', 'Fransız Tostu', 'French Toast', 229, 7.7, 25, 10.8, 1.7, 'grain', true, NOW(), NOW()),
  ('Omelet', 'Omlet', 'Omelet', 154, 13, 1, 11, 0, 'protein', true, NOW(), NOW()),
  ('Scrambled Eggs', 'Çırpılmış Yumurta', 'Scrambled Eggs', 154, 13, 1, 11, 0, 'protein', true, NOW(), NOW()),
  ('Fried Eggs', 'Kızarmış Yumurta', 'Fried Eggs', 154, 13, 1, 11, 0, 'protein', true, NOW(), NOW()),
  ('Poached Eggs', 'Poşe Yumurta', 'Poached Eggs', 154, 13, 1, 11, 0, 'protein', true, NOW(), NOW()),
  ('Bacon', 'Pastırma', 'Bacon', 541, 37, 1.4, 42, 0, 'protein', true, NOW(), NOW()),
  ('Sausage', 'Sosis', 'Sausage', 280, 15, 3, 22, 0, 'protein', true, NOW(), NOW()),
  ('Ham', 'Jambon', 'Ham', 250, 18, 2, 18, 0, 'protein', true, NOW(), NOW()),
  ('Hash Browns', 'Haşlanmış Patates', 'Hash Browns', 326, 3, 35, 19, 3.2, 'grain', true, NOW(), NOW()),
  ('Home Fries', 'Ev Patatesi', 'Home Fries', 326, 3, 35, 19, 3.2, 'grain', true, NOW(), NOW()),
  ('Cereal, Corn Flakes', 'Mısır Gevreci', 'Cereal, Corn Flakes', 357, 7.5, 84, 0.9, 3, 'grain', true, NOW(), NOW()),
  ('Cereal, Oatmeal', 'Yulaf Ezmesi', 'Cereal, Oatmeal', 389, 16.9, 66.3, 6.9, 10.6, 'grain', true, NOW(), NOW()),
  ('Granola', 'Granola', 'Granola', 471, 10, 64, 20, 5, 'grain', true, NOW(), NOW()),
  ('Potato Chips', 'Patates Cipsi', 'Potato Chips', 536, 7, 53, 34, 4.8, 'snack', true, NOW(), NOW()),
  ('Tortilla Chips', 'Tortilla Cipsi', 'Tortilla Chips', 536, 7, 53, 34, 4.8, 'snack', true, NOW(), NOW()),
  ('Pretzels', 'Pretzel', 'Pretzels', 380, 11, 79, 2.8, 2.8, 'snack', true, NOW(), NOW()),
  ('Popcorn', 'Patlamış Mısır', 'Popcorn', 387, 12.9, 77.8, 4.5, 14.5, 'snack', true, NOW(), NOW()),
  ('Trail Mix', 'Yol Karışımı', 'Trail Mix', 462, 13.8, 44.9, 29.8, 5, 'snack', true, NOW(), NOW()),
  ('Mixed Nuts', 'Karışık Kuruyemiş', 'Mixed Nuts', 607, 20, 21, 54, 7, 'snack', true, NOW(), NOW()),
  ('Crackers', 'Kraker', 'Crackers', 421, 10, 71, 11, 2.5, 'snack', true, NOW(), NOW()),
  ('Rice Cakes', 'Pirinç Keki', 'Rice Cakes', 387, 8, 81, 2.8, 0.7, 'snack', true, NOW(), NOW()),
  ('Granola Bars', 'Granola Barı', 'Granola Bars', 471, 10, 64, 20, 5, 'snack', true, NOW(), NOW()),
  ('Energy Bars', 'Enerji Barı', 'Energy Bars', 400, 20, 45, 15, 5, 'snack', true, NOW(), NOW()),
  ('Ketchup', 'Ketçap', 'Ketchup', 112, 1.7, 27.4, 0.1, 0.3, 'seasoning', true, NOW(), NOW()),
  ('Mustard', 'Hardal', 'Mustard', 66, 4, 5, 3.7, 3, 'seasoning', true, NOW(), NOW()),
  ('Mayonnaise', 'Mayonez', 'Mayonnaise', 680, 1, 0.6, 75, 0, 'seasoning', true, NOW(), NOW()),
  ('Olive Oil', 'Zeytinyağı', 'Olive Oil', 884, 0, 0, 100, 0, 'seasoning', true, NOW(), NOW()),
  ('Canola Oil', 'Kanola Yağı', 'Canola Oil', 884, 0, 0, 100, 0, 'seasoning', true, NOW(), NOW()),
  ('Vegetable Oil', 'Bitkisel Yağ', 'Vegetable Oil', 884, 0, 0, 100, 0, 'seasoning', true, NOW(), NOW()),
  ('Butter', 'Tereyağı', 'Butter', 717, 0.9, 0.1, 81, 0, 'seasoning', true, NOW(), NOW()),
  ('Honey', 'Bal', 'Honey', 304, 0.3, 82.4, 0, 0.2, 'seasoning', true, NOW(), NOW()),
  ('Maple Syrup', 'Akçaağaç Şurubu', 'Maple Syrup', 260, 0, 67, 0, 0, 'seasoning', true, NOW(), NOW()),
  ('Sugar', 'Şeker', 'Sugar', 387, 0, 100, 0, 0, 'seasoning', true, NOW(), NOW()),
  ('Salt', 'Tuz', 'Salt', 0, 0, 0, 0, 0, 'seasoning', true, NOW(), NOW()),
  ('Black Pepper', 'Karabiber', 'Black Pepper', 251, 10.4, 63.9, 3.3, 25.3, 'seasoning', true, NOW(), NOW()),
  ('Garlic Powder', 'Sarımsak Tozu', 'Garlic Powder', 331, 16.6, 72.7, 0.7, 2.1, 'seasoning', true, NOW(), NOW()),
  ('Onion Powder', 'Soğan Tozu', 'Onion Powder', 341, 10.4, 79.1, 1.0, 15.2, 'seasoning', true, NOW(), NOW()),
  ('Paprika', 'Kırmızı Biber', 'Paprika', 282, 14.1, 53.9, 12.9, 34.9, 'seasoning', true, NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

-- Statistics
SELECT COUNT(*) as total_foods FROM foods WHERE is_active = true;
